#!/bin/bash

user=`whoami`

if [ "$user" = "root" ]

then

	echo " You are a root user, Now we will install wordpress"

else

	sudo -i

fi
# we need to check LEMP 

/etc/init.d/nginx start

if [ $? -eq 0 ]

then

	echo " nginx is running "

else

	apt-get update && apt-get install nginx

fi
apt-get purge mysql-client-5.5
apt-get purge mysql-server-5.5
apt-get autoremove
apt-get autoclean
apt-get remove mysql-server
apt-get update && apt-get upgrade
echo " I know that, now there is no need of if statement below cause mysql is not present, we can comment it also"
/etc/init.d/mysql start

if [ $? -eq 0 ]

then

	echo " service mysql is running"

else

	apt-get install mysql-server && mysql_install_db && mysql_secure_installation && /etc/init.d/mysql restart

fi

/etc/init.d/php-fpm start

if [ $? -eq 0 ]

then

	echo " service php is running "

else 

	apt-get install php-fpm php5-mysql

fi

#  Enter Domain Name

echo " Enter Domain Name "

read domain_name

echo " Enter IP address"

read ip_address

# IP to Doamin name Pointing

echo "$ip_address $domain_name" >> /etc/hosts

# Mysql Database Creation
mysql -u root -p -e "CREATE USER 'sameer' IDENTIFIED BY 'redhat@123'";
mysql -u root -p -e "GRANT ALL PRIVILEGES ON *.* TO 'sameer'";
mysql -u root -p -e "FLUSH PRIVILEGES";
echo "login with user sameer,password redhat@123"
mysql -u sameer -p -e "CREATE DATABASE example_db";


# Downloading WordPress
cd ~
apt-get install wget
wget  http://wordpress.org/latest.zip
apt-get install unzip
unzip latest.zip
mkdir -p /var/www/html
apt-get install rsync
rsync -avP /root/wordpress/ /var/www/html/
cd /var/www/html/

# Changing Permission and ownership

chown -R root:www-data /var/www/html/*
mkdir wp-content/uploads
chown -R :www-data /var/www/html/wp-content/uploads

cd ~

# wordpress setup

cp -rv /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
cd /var/www/html/
sed -i 's/database_name_here/example_db/g' wp-config.php 
sed -i 's/username_here/sameer/g' wp-config.php
sed -i 's/password_here/redhat@123/g' wp-config.php
sed –i “s/localhost/$domain_name/g” wp-config.php

# nginx confiuration file

mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup.conf
cat > /etc/nginx/sites-available/default << EOF
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /var/www/html;
        index index.php index.html index.htm;

        server_name $domain_name;

        location / {
                # try_files $uri $uri/ =404;
                try_files $uri $uri/ /index.php?q=$uri&$args;
        }

        error_page 404 /404.html;

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
                root /usr/share/nginx/html;
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
        }
}
EOF
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled
bash /etc/nginx/sites-available/default -t
/etc/init.d/nginx restart
/etc/init.d/php5-fpm restart
